### ISSUE TITLE
[Bug]: Extensions tab nor behaving properly

### ISSUE THREAD

**Issue by Butterfly-Dragon** [Navezjt/stable-diffusion-webui-ux#1]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

When accessing the extensions tab i cannot click on the installed extensions and i cannot even update or uninstall them. moreover whenever trying to run any prompt i get this error.
```
*** Error running before_process: D:\Documents\GitHub\stable-diffusion-webui-ux\extensions-builtin\extra-options-section\scripts\extra_options_section.py
    Traceback (most recent call last):
      File "D:\Documents\GitHub\stable-diffusion-webui-ux\modules\scripts.py", line 467, in before_process
        script.before_process(p, *script_args)
      File "D:\Documents\GitHub\stable-diffusion-webui-ux\extensions-builtin\extra-options-section\scripts\extra_options_section.py", line 40, in before_process
        for name, value in zip(self.setting_names, args):
    TypeError: 'NoneType' object is not iterable
```

### Steps to reproduce the problem

1. Go to `Extensions` Tab
2. Try to interact with any installed extesion
3. nothing happens

### What should have happened?

previously i had the list of enabled and disabled extensions as green filled squares or white squares and whenever clicking on any of the squares i could enable or disable an extension and/or update it in case of new commits. That is  not the case now.

### Commit where the problem happens

v1.3.2-510-g355c0efe

### What Python version are you running on ?

Python 3.10.x

### What platforms do you use to access the UI ?

Windows

### What device are you running WebUI on?

Nvidia GPUs (RTX 20 above)

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--xformers --reinstall-xformers
```

### List of extensions

```
Stable-Diffusion-Webui-Civitai-Helper	https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper.git	main	[920ca326](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/commit/920ca3267f789a72e3225c99f069bf0be0db795d)	Tue May 23 11:53:22 2023	latest

a1111-stable-diffusion-webui-vram-estimator	https://github.com/space-nuko/a1111-stable-diffusion-webui-vram-estimator.git	master	[bf8797a3](https://github.com/space-nuko/a1111-stable-diffusion-webui-vram-estimator/commit/bf8797a3f3286ed5fd0519d9ad3650e30b84ef91)	Sun Mar 5 03:42:33 2023	unknown

model-keyword	https://github.com/mix1009/model-keyword.git	main	[0fa161a6](https://github.com/mix1009/model-keyword/commit/0fa161a601c64d5813ce2a84a70b9dee9ad39e67)	Sun May 28 06:00:46 2023	unknown

sd-model-preview-xd	https://github.com/CurtisDS/sd-model-preview-xd	main	[3ed39cd0](https://github.com/CurtisDS/sd-model-preview-xd/commit/3ed39cd0f6c20f4212e29141501e710ef91383af)	Tue May 23 00:52:25 2023	unknown

sd-webui-additional-networks	https://github.com/kohya-ss/sd-webui-additional-networks.git	main	[e9f3d622](https://github.com/kohya-ss/sd-webui-additional-networks/commit/e9f3d622b5a98650008a685ea23b27eb810da35a)	Tue May 23 12:31:15 2023	latest

sd-webui-ar	https://github.com/alemelis/sd-webui-ar.git	main	[9df49dc2](https://github.com/alemelis/sd-webui-ar/commit/9df49dc2d7da7333ac918fbce926c2370a3b8b53)	Wed Apr 12 09:23:17 2023	latest

sd-webui-prompt-all-in-one	https://github.com/Physton/sd-webui-prompt-all-in-one	main	[30acf430](https://github.com/Physton/sd-webui-prompt-all-in-one/commit/30acf430e0c3883f9141592b00784914e18b951b)	Fri May 26 05:57:59 2023	new commits

LDSR	[built-in](http://127.0.0.1:7860/)	None		Sat Jun 17 16:01:12 2023	

Lora	[built-in](http://127.0.0.1:7860/)	None		Sat Jun 17 16:01:12 2023	

ScuNET	[built-in](http://127.0.0.1:7860/)	None		Sat Jun 17 16:01:12 2023	

SwinIR	[built-in](http://127.0.0.1:7860/)	None		Sat Jun 17 16:01:12 2023	

canvas-zoom-and-pan	[built-in](http://127.0.0.1:7860/)	None		Sat Jun 17 16:01:12 2023	

extra-options-section	[built-in](http://127.0.0.1:7860/)	None		Sat Jun 17 16:01:12 2023	

prompt-bracket-checker	[built-in](http://127.0.0.1:7860/)	None		Sat Jun 17 16:01:12 2023	

sd_theme_editor	[built-in](http://127.0.0.1:7860/)	None		Sat Jun 17 16:01:12 2023
```

### Console logs

```Shell
venv "D:\Documents\GitHub\stable-diffusion-webui-ux\venv\Scripts\Python.exe"
Python 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]
Version: v1.3.2-510-g355c0efe
Commit hash: 355c0efed9f185d0f2259aa845e201ca44b53d49
Installing xformers
Collecting xformers==0.0.20
  Using cached xformers-0.0.20-cp310-cp310-win_amd64.whl (97.6 MB)
Installing collected packages: xformers
Successfully installed xformers-0.0.16rc425
Installing requirements

Launching Web UI with arguments: --xformers --reinstall-xformers
[AddNet] Updating model hashes...
0it [00:00, ?it/s]
[AddNet] Updating model hashes...
0it [00:00, ?it/s]
sd-webui-prompt-all-in-one background API service started successfully.
Loading weights [85b3bd1bba] from D:\Documents\GitHub\stable-diffusion-webui-ux\models\Stable-diffusion\Strange Dedication V4-Fp16.safetensors
Creating model from config: D:\Documents\GitHub\stable-diffusion-webui-ux\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying attention optimization: xformers... done.
Textual inversion embeddings loaded(12): bad-artist, bad-artist-anime, bad-hands-5, bad-image-v2-39000, bad_prompt_version2, EasyNegative, gloss_enhancer_v5, glossifier_v3, NG_DeepNegative_V1_4T, NG_DeepNegative_V1_64T, NG_DeepNegative_V1_75T, smokey_eyes_v1
Model loaded in 3.9s (load weights from disk: 1.0s, create model: 0.5s, apply weights to model: 0.6s, apply half(): 0.8s, move model to device: 0.9s).
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 11.5s (import torch: 1.5s, import gradio: 0.9s, import ldm: 1.7s, other imports: 0.7s, load scripts: 1.4s, create ui: 4.2s, gradio launch: 0.6s, app_started_callback: 0.3s).
preload_extensions_git_metadata for 15 extensions took 1.35s
*** Error running before_process: D:\Documents\GitHub\stable-diffusion-webui-ux\extensions-builtin\extra-options-section\scripts\extra_options_section.py
    Traceback (most recent call last):
      File "D:\Documents\GitHub\stable-diffusion-webui-ux\modules\scripts.py", line 467, in before_process
        script.before_process(p, *script_args)
      File "D:\Documents\GitHub\stable-diffusion-webui-ux\extensions-builtin\extra-options-section\scripts\extra_options_section.py", line 40, in before_process
        for name, value in zip(self.setting_names, args):
    TypeError: 'NoneType' object is not iterable

---
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 150/150 [00:57<00:00,  2.62it/s]
Total progress: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 150/150 [00:55<00:00,  2.72it/s]
*** Error running before_process: D:\Documents\GitHub\stable-diffusion-webui-ux\extensions-builtin\extra-options-section\scripts\extra_options_section.py█████████████████████████████████████████████████████████████████████████████████████████████████████████████| 150/150 [00:55<00:00,  2.77it/s]
    Traceback (most recent call last):
      File "D:\Documents\GitHub\stable-diffusion-webui-ux\modules\scripts.py", line 467, in before_process
        script.before_process(p, *script_args)
      File "D:\Documents\GitHub\stable-diffusion-webui-ux\extensions-builtin\extra-options-section\scripts\extra_options_section.py", line 40, in before_process
        for name, value in zip(self.setting_names, args):
    TypeError: 'NoneType' object is not iterable

---
Calculating sha256 for D:\Documents\GitHub\stable-diffusion-webui-ux\models\Lora\NAI-cutesexyrobutts.safetensors: 771f04b1682288d77fd48ba62e57ae4a5fd5a0a6d6976e823fa9fee01bbf60f6
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 150/150 [00:52<00:00,  2.83it/s]
Total progress: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 150/150 [00:52<00:00,  2.85it/s]
*** Error running before_process: D:\Documents\GitHub\stable-diffusion-webui-ux\extensions-builtin\extra-options-section\scripts\extra_options_section.py█████████████████████████████████████████████████████████████████████████████████████████████████████████████| 150/150 [00:52<00:00,  2.58it/s]
    Traceback (most recent call last):
      File "D:\Documents\GitHub\stable-diffusion-webui-ux\modules\scripts.py", line 467, in before_process
        script.before_process(p, *script_args)
      File "D:\Documents\GitHub\stable-diffusion-webui-ux\extensions-builtin\extra-options-section\scripts\extra_options_section.py", line 40, in before_process
        for name, value in zip(self.setting_names, args):
    TypeError: 'NoneType' object is not iterable

---
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 150/150 [00:55<00:00,  2.73it/s]
Total progress: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 150/150 [00:54<00:00,  2.74it/s]
*** Error running before_process: D:\Documents\GitHub\stable-diffusion-webui-ux\extensions-builtin\extra-options-section\scripts\extra_options_section.py█████████████████████████████████████████████████████████████████████████████████████████████████████████████| 150/150 [00:54<00:00,  2.66it/s]
    Traceback (most recent call last):
      File "D:\Documents\GitHub\stable-diffusion-webui-ux\modules\scripts.py", line 467, in before_process
        script.before_process(p, *script_args)
      File "D:\Documents\GitHub\stable-diffusion-webui-ux\extensions-builtin\extra-options-section\scripts\extra_options_section.py", line 40, in before_process
        for name, value in zip(self.setting_names, args):
    TypeError: 'NoneType' object is not iterable

---
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 150/150 [01:00<00:00,  2.47it/s]
Total progress: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 150/150 [01:00<00:00,  2.47it/s]
*** Error running before_process: D:\Documents\GitHub\stable-diffusion-webui-ux\extensions-builtin\extra-options-section\scripts\extra_options_section.py█████████████████████████████████████████████████████████████████████████████████████████████████████████████| 150/150 [01:00<00:00,  1.22it/s]
    Traceback (most recent call last):
      File "D:\Documents\GitHub\stable-diffusion-webui-ux\modules\scripts.py", line 467, in before_process
        script.before_process(p, *script_args)
      File "D:\Documents\GitHub\stable-diffusion-webui-ux\extensions-builtin\extra-options-section\scripts\extra_options_section.py", line 40, in before_process
        for name, value in zip(self.setting_names, args):
    TypeError: 'NoneType' object is not iterable

---
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 150/150 [00:56<00:00,  2.64it/s]
Total progress: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 150/150 [00:56<00:00,  2.66it/s]
Total progress: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 150/150 [00:56<00:00,  1.95it/s]
```

**Comment by Butterfly-Dragon** [comment]
thanks!
